// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  item: string;
  item_description: string;
  item_icon: string;
  item_language_repo: string;
  item_last_updated: string;
  item_license_repo: string;
  item_link_repo: string;
  item_star_repo: string;
  item_status_repo: string;
  overall_result: string;
  result_list: string;
  result_list_item: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
