// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  loading: string;
  search_form: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
